# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo3

  # Pods for Alamofire
  pod 'Alamofire', '~>4.2.0'

  # Pods for Keychain
  pod ‘SwiftKeychainWrapper’

  target 'demo3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
