# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#my work
#source 'https://github.com/JessDF/JDOWDINGCOCOA.git'
target 'WorldTrotter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PCLBlurEffectAlert', '~> 2.1'
  pod "JDOWDINGCOCOA", :path => 'JDOWDINGCOCOA'

  target 'WorldTrotterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorldTrotterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
