# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireAPIWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireAPIWeather
  pod 'Alamofire', '~>4.2.0'

  target 'AlamofireAPIWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamofireAPIWeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
